# Generated by Django 4.2.4 on 2023-08-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da forma de citar')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Funções',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da função de citar')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
    ]
