# Generated by Django 4.2.4 on 2023-08-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formas',
            name='citacao',
            field=models.TextField(default=0, verbose_name='Citação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formas',
            name='explicacao',
            field=models.TextField(default=0, verbose_name='Explicação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formas',
            name='referencia',
            field=models.TextField(default=0, verbose_name='Referência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funções',
            name='citacao',
            field=models.TextField(default=0, verbose_name='Citação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funções',
            name='referencia',
            field=models.TextField(default=0, verbose_name='Referência'),
            preserve_default=False,
        ),
    ]
