# Generated by Django 4.2.2 on 2023-09-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citar', '0003_plagio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integralidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da marcação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('citacao', models.TextField(verbose_name='Citação')),
                ('referencia', models.TextField(verbose_name='Referência')),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
    ]
