# Generated by Django 4.2.2 on 2023-09-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citar', '0004_integralidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integralidade',
        ),
    ]
