# Generated by Django 3.2.20 on 2023-09-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citar', '0006_sites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plagio',
            old_name='nome',
            new_name='nomePlagio',
        ),
    ]
