# Generated by Django 4.2.4 on 2023-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citar', '0007_rename_nome_plagio_nomeplagio'),
    ]

    operations = [
        migrations.AddField(
            model_name='formas',
            name='integralidade',
            field=models.BooleanField(default='', verbose_name='Integralidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sites',
            name='link',
            field=models.TextField(verbose_name='Link para acessar o site'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do site recomendado'),
        ),
    ]
