# Generated by Django 4.2.4 on 2023-09-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citar', '0008_formas_integralidade_alter_sites_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formas',
            name='integralidade',
        ),
    ]
