# Generated by Django 4.2.4 on 2023-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citar', '0009_remove_formas_integralidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do sistema de chamada')),
                ('explicacao', models.TextField(verbose_name='Explicação')),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
    ]
